export const contactsActionTypes = {
  INIT_CONTACTS: '[contacts] INIT_CONTACTS',
  INIT_CONTACTS_FILTER: '[contacts] INIT_CONTACTS_FILTER',
  SELECT_CONTACT: '[contacts] SELECT_CONTACT',
  SET_CONTACTS_FILTER: '[contacts] SET_FILTER',
  FILTER_OUT_CONTACTS: '[contacts] FILTER_OUT_CONTACTS'
};
